package com.axon.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Represents a structured educational lesson containing concepts, executable commands, and practice material.
 * <p>
 * This record functions as an immutable Data Transfer Object (DTO), typically used for mapping JSON data
 * to a Java object. It is annotated with {@link JsonIgnoreProperties} to gracefully handle and ignore
 * any unknown properties found in the source JSON, ensuring robustness against schema changes.
 * </p>
 *
 * @param title           The descriptive header or name of the lesson.
 * @param concept         The underlying theoretical concept or explanation being taught.
 * @param command         The primary command, code snippet, or instruction demonstrating the concept.
 * @param example_output  The expected standard output (stdout) or result generated by running the {@code command}.
 * @param practiceCommand An interactive exercise or challenge command for the user to attempt.
 * @param hint            Contextual assistance or a tip provided to help the user solve the {@code practiceCommand}.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record Lesson(
        String title,
        String concept,
        String command,
        String example_output,
        String practiceCommand,
        String hint
) {
}